<h2>Numpy  Operations</h2>

In [2]:
import numpy as np

In [5]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3>Array with Arrays</h3>

In [13]:
arr + arr # Le sumo al array el mismo array
arr - arr
arr * arr
#arr / arr # Numpy devuelve nan(nulo) en vez de error al hacer algo invalido como dividir por 0

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

<h3>Array with Scalars</h3>

In [10]:
arr + 100 # Le sumo 100 a cada elemento
arr - 100
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

<h3>Universal Array Functions</h3>

In [14]:
np.sqrt(arr) # Devuelve un nuevo arreglo con todos los elementos al cuadrado

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [15]:
np.exp(arr) # Devuelve un nuevo arreglo con el exponencial de cada elemento (e elevado al elemento)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [18]:
np.max(arr) # Devuelve el maximo
np.sin(arr) # Devuelve el seno de cada elemento. Tambien hay cos(), tan()....
np.log(arr)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14936\1948528802.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

https://docs.scipy.org/doc/numpy-1.10.1/reference/ufuncs.html