In [1]:
list = [1, 2, 3]

In [2]:
list

[1, 2, 3]

In [2]:
import numpy as np

In [5]:
array = np.array(list)

In [6]:
array

array([1, 2, 3])

In [7]:
matriz = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
### Una forma de crear arreglos
np.arange(3, 10, 2) # Crea un arreglo arrancando desde el primer numero hasta el segundo. El tercer parametro es opcional, es para hacer un intervalo, en este caso de dos en dos

array([3, 5, 7, 9])

In [13]:
### Generar un arreglo de ceros
np.zeros(3) # Va a generar un arreglo con tantos 0 como indique el parametro
np.zeros((5, 5)) # Va a generar matriz de 5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
### Generar arreglo de unos
np.ones(6)
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
### Linspace()
np.linspace(0, 10, 3) # Genera una arreglo empezando desde el primer argumento, hasta el segundo, del tamaño del tercer argumento proporcionalmente distribuidos

array([ 0.,  5., 10.])

In [7]:
### Generar matriz identidad
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
### Generar arreglos de numeros al azar
np.random.rand(3) # Arreglo unidimensional con numeros entre el 0 y 1
np.random.rand(5, 5)

array([[0.41780067, 0.86231242, 0.90463721, 0.37931465, 0.58948754],
       [0.24721269, 0.40074615, 0.26748174, 0.31629911, 0.86838449],
       [0.8933615 , 0.29154135, 0.77182355, 0.8023901 , 0.29795181],
       [0.15442448, 0.41103775, 0.64311635, 0.91285977, 0.42830021],
       [0.76077633, 0.82263235, 0.25855624, 0.71981003, 0.76782065]])

In [11]:
### Return a sample (or samples) from the “standard normal” distribution.
np.random.randn(5)
np.random.randn(5,5)

array([[ 0.24527603, -1.65081238,  2.36424951, -1.28815631,  1.34521996],
       [-0.50625717,  0.8072174 , -1.05261279, -0.78261497,  1.16245235],
       [-1.58936336,  1.1335555 , -0.48216802,  0.31016787,  0.80136873],
       [ 1.62571585, -0.44500759,  0.0194834 , -0.19523362,  1.15800261],
       [-0.65874812,  2.31894914, -0.00918392, -0.35531014,  0.83550346]])

In [13]:
### Generar arreglo de enteros al azar
np.random.randint(0, 101, 55) # 55 numeron enteros al azar entre el 0 y 101

array([10,  0, 72, 47, 67, 39, 39, 89, 71,  0, 21, 54, 85, 73, 16, 47, 71,
       47, 10, 93, 96, 89, 29, 19, 59, 74, 76, 52, 44, 46, 82, 19, 65, 53,
        2, 78, 97, 16,  2, 48, 46, 10, 79, 42, 45, 78, 50, 78, 67, 97, 68,
       19, 99, 37, 54])

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([ 1,  2, 44,  4, 28,  1, 38, 18, 37, 38])

In [18]:
## reshape()
arr.reshape(5, 5) # La cantidad de elementos del nuevo tamaño debe ser igual al anterior

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ranarr.max()

44

In [20]:
ranarr.min()

1

In [21]:
ranarr.argmax()

2

In [22]:
ranarr.argmin()

0

In [26]:
arr.shape
ranarr.shape

(10,)