In [1]:
import numpy as np

In [9]:
arr = np.arange(0, 11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0] # Elemento en la posicion 0

0

In [12]:
arr[1:6] # Elementos de la posicion 1 a 5

array([1, 2, 3, 4, 5])

In [13]:
arr[:6] # Elementos desde el inicio hasta posicion 5

array([0, 1, 2, 3, 4, 5])

In [14]:
arr[6:] # Elementos de la posicion 6 hasta el final

array([ 6,  7,  8,  9, 10])

In [15]:
arr[0:5] = 100 # Sobreescribo los elementos de indices 0 a 5 con 100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange(0, 11)

In [18]:
sliceArr = arr[0:5]

In [19]:
sliceArr[:] 

array([0, 1, 2, 3, 4])

In [20]:
sliceArr[:] = 100 # Cambia ademas el arreglo original. Los datos no son una copia, si no una vista al arreglo original

In [21]:
sliceArr

array([100, 100, 100, 100, 100])

In [22]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [23]:
arr_copy = arr.copy() # Para copiar el arreglo y que no sea una vista

In [26]:
arr_copy[:5] = 110

In [27]:
arr_copy

array([110, 110, 110, 110, 110,   5,   6,   7,   8,   9,  10])

In [28]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [2]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

<h3>Sub Matriz</h3>

In [10]:
arr_2d[0][0]

5

In [5]:
arr_2d[0,0] # [0, 0] equivale a [0][0]

5

In [21]:
arr_2d[:2,1:]
arr_2d[1:,:2]
arr_2d[:,2]

array([15, 30, 45])

<h3>Conditional Selection</h3>

In [25]:
arr = np.arange(1, 11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
bool_arr = arr > 5 # Devuelve un arreglo de booleanos

In [29]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr] # Me quedo con lo elementos del arreglo que cumplen la validacion

array([ 6,  7,  8,  9, 10])

In [31]:
arr[arr>5] # Simplificado

array([ 6,  7,  8,  9, 10])